version: '3.8'
services:
  mysql:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=gsfranzoni
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
    driver: local